# Travis-CI Builder

# We will refrain from using java 7 till further notice
language: java
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7

# Clean, test
# Submit Coveralls and JaCoCo report
after_success:
  - mvn clean test jacoco:report coveralls:report
